name: hosptel_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  curved_labeled_navigation_bar: ^2.0.2
  dartz: ^0.10.1
  double_back_to_exit: ^1.0.0
  dropdown_button2: ^2.3.8
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  google_fonts: 6.1.0
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  logger: ^2.2.0
  pin_code_fields: ^8.0.1
  rename: ^3.0.2
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0
  stroke_text: any

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/image/png/
    - assets/image/svg/

  # example:
  fonts:
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf

    - family: TajawalLight
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf

    - family: TajawalRegular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: TajawalMedium
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf

    - family: TajawalBold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
